### ISSUE TITLE
Developed with JRuby then deployed to MRI Ruby

### ISSUE THREAD

**Issue by Azolo** [shanselman/march-is-for-makers#1]
It's probably causing errors when you try to use Bundler.

I'm guessing it's why you're using `bundle update` instead of `bundle install`

The remedy is probably to `bundle update` with MRI Ruby, commit `Gemfile.lock` then deploy, or to add `Gemfile.lock` to your `.gitignore`.

The `platforms` section in your `Gemfile.lock` should read something like `x64-mingw32`

Either way `bundle install` should stop giving you fits that way.

**Comment by shanselman** [comment]
Super helpful issues, thanks so much for your time! I'll try to get them fixed/rolled up this week!

**Comment by Azolo** [comment]
Sure, thing. Someone mentioned it in the RubyInstaller mailing list and asked if someone could take a look. Honestly, deploying Bootstrapping Ruby can be pretty painful. 

But if you have any RubyInstaller type questions just mention me and I'll do what I can to help.

**Comment by shanselman** [comment]
@Azolo Very kind. I think if I get this correct, it'll be useful for folks. However, as you know, Ruby and Windows seem to REALLY not like each other. ;)

**Comment by shanselman** [comment]
Right now I'm trying to figure how to get Bundle to stop adding java to the gemfile.lock.

**Comment by Azolo** [comment]
It probably just means that the you have a jruby `bundle.bat` in your path before MRI `bundle`

Run `where.exe bundle`

**Comment by shanselman** [comment]
@Azolo Yep, just figured that out. Thanks for your patience and help!

**Comment by Azolo** [comment]
No problem. I still have that problem sometimes.
