### ISSUE TITLE
Ruby Install Not Working

### ISSUE THREAD

**Issue by martincostello** [shanselman/march-is-for-makers#5]
While following the instructions in [this](http://www.hanselman.com/blog/RunningTheRubyMiddlemanStaticSiteGeneratorOnMicrosoftAzure.aspx) blog post to set up a Git deployment for Middleman for my own blog in Azure I found a few issues during the process that I had to resolve in the [getruby.cmd](https://github.com/shanselman/march-is-for-makers/blob/master/getruby.cmd) file that I have copied and added to my own repo.

These were:
1. Ruby failing to be downloaded by cURL due to a 302 redirect;
2. Ruby failing to extract due to invalid 7zip command line arguments;
3. Some gems with native extensions failing to install due to `'bundle' is not recognized as an internal or external command, operable program or batch file.`  errors (specifically with the `json` and `eventmachine` gems). I presume something in the Ruby tool chain wasn't picking up the modified `PATH` variable.

I couldn't get to the bottom of the third problem, but I was able to use Kudu to manually run `gem install json` and `gem install eventmachine` manually by `cd`'ing into the `bin` folder of the Ruby install.

PR that fixes 1 and 2 to follow.

**Comment by martincostello** [comment]
Just to say, other than these problems, this script and the blog post I found it from were fantastic for setting up my blog deployment!

**Comment by shanselman** [comment]
Weird on #1 and #2 because this is LITERALLY what I'm running in Production now. Not sure why it wouldn't work for you.

**Comment by martincostello** [comment]
If it helps highlight any difference, my site outputs this when connecting via Kudu for cURL:

```
Kudu Remote Execution Console
Type 'exit' then hit 'enter' to get a new CMD process.
Type 'cls' to clear the console

Microsoft Windows [Version 6.2.9200]

(c) 2012 Microsoft Corporation. All rights reserved.



D:\home>curl --version
curl 7.30.0 (i386-pc-win32) libcurl/7.30.0 OpenSSL/0.9.8y zlib/1.2.7

Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smtp smtps telnet tftp 

Features: AsynchDNS GSS-Negotiate IPv6 Largefile NTLM SPNEGO SSL SSPI libz 


```
